DROP DATABASE IF EXISTS PHOTO_BUCKET;
CREATE DATABASE PHOTO_BUCKET;
USE PHOTO_BUCKET;

CREATE TABLE USUARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(50) NOT NULL UNIQUE,
    CORREO VARCHAR(250) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(250) NOT NULL,
    IMAGEN VARCHAR(250) NOT NULL,
    RECACTIVO BOOLEAN NOT NULL DEFAULT FALSE,
    RECIMAGEN VARCHAR(250),
    CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ALBUM (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    USUARIO INT NOT NULL,
    CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE IMAGEN (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(250),
    IMAGEN VARCHAR(250) NOT NULL,
    ALBUM INT NOT NULL,
    CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ALBUM) REFERENCES ALBUM(ID)
);